pipeline:
  - name: ircc
    watchdog: 600
    steps:
      - name: clone
        run: |
          rm -rf /tmp/ircc
          git clone https://github.com/mirmik/ircc /tmp/ircc

      - name: cmake
        run: |
          cd /tmp/ircc
          cmake .

      - name: cmake-build
        run: |
          cd /tmp/ircc
          cmake --build .

      - name: cmake-tests
        run: |
          cd /tmp/ircc
          ctest .
