pipeline_template:
  - name: netricks_library
    watchdog: 600
    steps:
      - name: clone
        run: |
          rm -rf {{workspace}}/{{libname}}
          git clone https://github.com/mirmik/{{libname}} {{workspace}}/{{libname}}

      - name: get_commit_hash
        set_variable: commit_hash
        script: |
          cd {{workspace}}/{{libname}}
          git rev-parse HEAD

      - name: get_commit_message
        set_variable: commit_message
        script: |
          cd {{workspace}}/{{libname}}
          git log -1 --pretty=%B

      - name: cmake
        run: |
          cd {{workspace}}/{{libname}}
          cmake .

      - name: cmake-build
        run: |
          cd {{workspace}}/{{libname}}
          cmake --build .

      - name: cmake-install
        run: |
          cd {{workspace}}/{{libname}}
          cmake --build . --target install

      - name: cmake-tests
        run: |
          cd {{workspace}}/{{libname}}
          ctest .

    success_info: "Pipeline: {{libname}}\nCommit: {{commit_hash}}\nMessage: {{commit_message}}\n"

pipeline:
  - name: igris
    use_template: netricks_library
    args:
      libname: igris

  - name: nos
    use_template: netricks_library
    args:
      libname: nos

  - name: crow
    use_template: netricks_library
    args:
      libname: crow

  - name: ralgo
    use_template: netricks_library
    args:
      libname: ralgo

  - name: rabbit
    use_template: netricks_library
    args:
      libname: rabbit
